# Generated by Django 4.2.15 on 2024-09-11 19:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
