# Generated by Django 4.2.15 on 2024-11-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_tweet_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helpcenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='help_images/')),
                ('is_checked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(null=True, upload_to='event_images/'),
        ),
    ]
