# Generated by Django 4.2.15 on 2024-11-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_helpcenter_is_checked_alter_helpcenter_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpcenter',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
